[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/oparl/*"
  to = "https://buergerinfo.stadt-koeln.de/oparl/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
